### ISSUE TITLE
Documentation Bugs: Testing and Slot Type Name 

### ISSUE THREAD

**Issue by cheruvian** [alexa-games/litexa#144]
# Bug Report
* Couple of the links under the [Testing reference](https://www.litexa.com/book/testing.html#litexa-test-statements) are broken.
  * `LISTEN`
  * `database variables`
* [`user:` language reference](https://www.litexa.com/reference/#user)
  * Broken example `$name = Cat` should be `$name = "Cat"`
  * Missing example of slot values
  * Missing documentation of how to trigger `otherwise` test case (any intent in the skill)
     * Does this mean if there is no way to trigger otherwise if all intents are valid for a state?
* [Slot Builder Type naming is incorrect in the docs](https://www.litexa.com/book/state-management.html#slots) says that for a slot `$thing` it will generate a `thingType` type in my experience however (At least for slotbuilder types) it instead creates `THING` type

**Comment by joseifert** [comment]
Thanks for reporting the above issues, cheruvian. Please take a look at the changes in the above PR and provide feedback, if you'd like to.

1. Fixed the broken links.
2. Updated Language Reference with some more details for slot values and how to test an `otherwise` handler. This can currently only be done by using a valid skill intent that isn't handled in the state being tested, since that directly represents how it would be triggered by a user in the live skill. We can further discuss in #145 if you'd prefer a different approach.

Regarding your comment about `$thing` converting to "THING": Any standalone slot declaration such as `with $thing = "sphere"` or `with $thing = "sphere", "cube"` should convert to `thingType` as you can confirm with the `litexa model` CLI command, or by checking the ASK Developer Console once you've deployed your skill.

If you're using a slot builder, it will use the "name" you've specified in the slot builder function, as documented here: https://litexa.com/book/state-management.html#slots

If you're seeing different behavior, please provide further details of how you're building your custom slot.

**Comment by cheruvian** [comment]
I see, that makes sense can we make an update to make that more explicit?

Perhaps this can be separated into a follow up issue to use a standardized function definition syntax like [jsdoc](https://jsdoc.app/tags-param.html)

From what I understand it would be something along the lines of:

```
/**
 * @typedef {Object} SlotDefinition
 * @property {string} name - The Slot Type Name used throughout your *.litexa files after the first slot builder load
 * @property {string[]} values - The Slot Values used for training your skill model. Be sure that any slot values used in your sample phrases are included here or you will fail certification.
 */
 /**
  * @param skill Information about the skill being built by litexa
  * @param skill.projectInfo.root The root of the current litexa project being built.
  * @param language The language of the current litexa deployment/project determined by LINK_TO_LOCALIZATION docs
  * @returns {SlotDefinition} The Slot Definition
  */
function yourSlotBuilderFunctionReference(skill, language){
...
}
```

Alternatively we could create a `@typedef` for skill as well

This probably becomes a duplicate of https://github.com/alexa-games/litexa/issues/21
