### ISSUE TITLE
Bug: Icon upload error on demo projects

### ISSUE THREAD

**Issue by kazlan** [alexa-games/litexa#75]
Hi, I know it must be something utterly stupid on my side but I can't get demo projects to deploy on aws. I've tried in both macos and Windows WSL environments with the same error message.

`[manifest] +3883ms [
  {
    "message": "Resource with identifier \"https://s3.us-east-1.amazonaws.com/inheron/cuantopaGas/development/default/icon-108.png\" at property path \"$.manifest.publishingInformation.locales.en-US.smallIconUri\" has invalid content type. Allowed content types: [\"image/png\"]."
  },
  {
    "message": "Resource with identifier \"https://s3.us-east-1.amazonaws.com/inheron/cuantopaGas/development/default/icon-512.png\" at property path \"$.manifest.publishingInformation.locales.en-US.largeIconUri\" has invalid content type. Allowed content types: [\"image/png\"]."
  }
]
[manifest] +11ms "skill in FAILED state"
[deploy] +14215ms failed manifest deployment`

**Comment by joseifert** [comment]
Hello @kazlan!

The error you're seeing is a SMAPI error (https://developer.amazon.com/docs/smapi/error-codes.html#invalid_content_type), which was apparently returned as Litexa was attempting to deploy your skill manifest.

It looks like SMAPI is complaining about your skill icon not being readable, which might be due to the asset in your S3 bucket not being accessible. Could you please verify that the asset `https://s3.us-east-1.amazonaws.com/inheron/cuantopaGas/development/default/icon-108.png` exists in your AWS S3 bucket, and is set to public?

As an FYI, there are currently 2 ways you can add skill icons (required by SMAPI) to an Litexa-built skill.

1) You can include icon-108.png and icon-512.png files in your "assets" directory. Default placeholder files are included in a `litexa generate`d project, but can be swapped. If you ran a full `litexa deploy` or a partial `litexa deploy -t assets`, the 2 placeholder skill icon image files should have been auto-deployed to your S3 bucket and set to public.

2) Alternatively, you can add entries in the skill manifest (found in the `skill*` file of your project's root directory) to point to any existing image URLs as follows:
```js
publishingInformation: {
  locales: {
    'en-US': {
      /* ... */
      smallIconUri: 'https://s3.amazonaws.com/.../icon-108.png',
      largeIconUri: 'https://s3.amazonaws.com/.../icon-512.png'
    }
  }
}
```

Please let us know if you have any remaining issues/questions.

**Comment by greghroberts** [comment]
@kazlan Let us know if this resolves your issue, thanks!

**Comment by greghroberts** [comment]
Resolving as no further questions.
